// Catppuccin Mocha palette
export const colors = {
  base: '#1e1e2e',
  mantle: '#181825',
  crust: '#11111b',
  surface0: '#313244',
  surface1: '#45475a',
  surface2: '#585b70',
  overlay0: '#6c7086',
  overlay1: '#7f849c',
  overlay2: '#9399b2',
  subtext0: '#a6adc8',
  subtext1: '#bac2de',
  text: '#cdd6f4',
  lavender: '#b4befe',
  blue: '#89b4fa',
  sapphire: '#74c7ec',
  sky: '#89dceb',
  teal: '#94e2d5',
  green: '#a6e3a1',
  yellow: '#f9e2af',
  peach: '#fab387',
  maroon: '#eba0ac',
  red: '#f38ba8',
  mauve: '#cba6f7',
  pink: '#f5c2e7',
  flamingo: '#f2cdcd',
  rosewater: '#f5e0dc',
};

export const statusColors: Record<string, string> = {
  idle: colors.blue,
  working: colors.green,
  waiting: colors.yellow,
  stopped: colors.overlay0,
  error: colors.red,
  pending: colors.yellow,
  assigned: colors.blue,
  in_progress: colors.green,
  completed: colors.teal,
  failed: colors.red,
  canceled: colors.overlay0,
};

export const baseStyles = {
  container: {
    backgroundColor: colors.base,
    color: colors.text,
    minHeight: '100vh',
    fontFamily: "'Inter', 'Segoe UI', system-ui, sans-serif",
  },
  card: {
    backgroundColor: colors.surface0,
    borderRadius: '8px',
    padding: '16px',
    border: `1px solid ${colors.surface1}`,
  },
  input: {
    backgroundColor: colors.mantle,
    color: colors.text,
    border: `1px solid ${colors.surface1}`,
    borderRadius: '6px',
    padding: '8px 12px',
    fontSize: '14px',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  button: {
    primary: {
      backgroundColor: colors.blue,
      color: colors.base,
      border: 'none',
      borderRadius: '6px',
      padding: '8px 16px',
      fontSize: '14px',
      fontWeight: '600',
      cursor: 'pointer',
    },
    secondary: {
      backgroundColor: colors.surface1,
      color: colors.text,
      border: 'none',
      borderRadius: '6px',
      padding: '8px 16px',
      fontSize: '14px',
      cursor: 'pointer',
    },
    danger: {
      backgroundColor: colors.red,
      color: colors.base,
      border: 'none',
      borderRadius: '6px',
      padding: '8px 16px',
      fontSize: '14px',
      fontWeight: '600',
      cursor: 'pointer',
    },
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    fontSize: '14px',
  },
  th: {
    padding: '10px 12px',
    textAlign: 'left' as const,
    color: colors.subtext0,
    fontWeight: '500',
    borderBottom: `1px solid ${colors.surface1}`,
    fontSize: '12px',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  td: {
    padding: '10px 12px',
    borderBottom: `1px solid ${colors.surface0}`,
    color: colors.text,
  },
};
